
DATASET:
  DATASET_NAME: Vigne # or outdoor
  IMAGE_PATH: '/home/mx1d/Unet/data/dataset_segmantation_outdoor/image/'
  MASK_PATH: '/home/mx1d/Unet/data/dataset_segmantation_outdoor/mask/'
  NUM_CLASSES: 2

MODEL:
  NAME: Unet
  NUM_OUTPUTS: 1
  PRETRAINED: ''
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]

TRAIN:
  TRAIN_H_RESIZE: 384
  TRAIN_W_RESIZE: 512
  TRAIN_H: 512
  TRAIN_W: 512
  BATCH_SIZE: 4
  BEGIN_EPOCH: 0
  END_EPOCH: 30
  MAX_LR: 0.001 #1e-3
  WEIGHT_DECAY: 0.0001 #1e-4
  
TEST:
  TEST_H_RESIZE: 384
  TEST_W_RESIZE: 512
  TEST_H: 512
  TEST_W: 512
  TEST_GPU: [0]
  MODEL_PATH: /home/mx1d/Unet/unet_train/test.pt  # evaluation model path